# Generated by Django 6.1.1 on 2026-09-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
