# Generated by Django 6.1.1 on 2026-09-25 12:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredient_aliases'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcal', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('protein_g', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('carbs_g', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fat_g', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fiber_g', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('serving_size_g', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('source', models.CharField(max_length=200)),
                ('source_id', models.CharField(max_length=200)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='recipes.ingredient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ingredient', 'source', 'source_id'), name='unique_ingredient_nutrition_source'), models.CheckConstraint(condition=models.Q(('kcal__gte', 0), ('protein_g__gte', 0), ('carbs_g__gte', 0), ('fat_g__gte', 0), ('fiber_g__gte', 0), ('serving_size_g__gt', 0)), name='ingredient_nutrition_valid_values')],
            },
        ),
    ]
