# Generated by Django 6.1.1 on 2026-10-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientnutrition',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
