# Generated by Django 6.1.1 on 2026-10-05 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_ingredientnutrition_publication_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientnutrition',
            name='ingredient_nutrition_valid_values',
        ),
        migrations.AlterField(
            model_name='ingredientnutrition',
            name='carbs_g',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ingredientnutrition',
            name='fat_g',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ingredientnutrition',
            name='fiber_g',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ingredientnutrition',
            name='kcal',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ingredientnutrition',
            name='protein_g',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='ingredientnutrition',
            constraint=models.CheckConstraint(condition=models.Q(('serving_size_g__gt', 0), models.Q(('kcal__isnull', True), ('kcal__gte', 0), _connector='OR'), models.Q(('protein_g__isnull', True), ('protein_g__gte', 0), _connector='OR'), models.Q(('carbs_g__isnull', True), ('carbs_g__gte', 0), _connector='OR'), models.Q(('fat_g__isnull', True), ('fat_g__gte', 0), _connector='OR'), models.Q(('fiber_g__isnull', True), ('fiber_g__gte', 0), _connector='OR')), name='ingredient_nutrition_valid_values'),
        ),
    ]
